baseURL = 'https://HOOTORO.github.io/'
languageCode = 'en-us'
title = 'Family'
theme = 'holy'
enableEmoji = true
enableGitInfo = true
watch = true

[params]
AuthorName = 'Mark'
GitHubUser = 'HOOTORO'
ListOfFoo = ['foo1', 'foo2']
SidebarRecentLimit = 5
Subtitle = 'Incoming Dates'
[permalinks]
posts = '/:year/:month/:title/'

[frontmatter]
date = ['date', 'publishDate', 'lastmod']
expiryDate = ['expiryDate']
lastmod = [':git', 'lastmod', 'date', 'publishDate']
publishDate = ['publishDate', 'date']

[menu]
[[menu.main]]
name = 'Home'
pageRef = '/'
weight = 10
[[menu.main]]
name = 'Dates'
pageRef = '/dates'
weight = 20
[[menu.main]]
name = 'Info'
pageRef = '/info'
weight = 30
[[menu.main]]
name = 'About'
pageRef = '/about'
weight = 90


[minify]
disableCSS = false
disableHTML = false
disableJS = false
disableJSON = false
disableSVG = false
disableXML = false
minifyOutput = false
[minify.tdewolff]
[minify.tdewolff.css]
keepCSS2 = true
precision = 0
[minify.tdewolff.html]
keepComments = false
keepConditionalComments = true
keepDefaultAttrVals = true
keepDocumentTags = true
keepEndTags = true
keepQuotes = false
keepWhitespace = false
[minify.tdewolff.js]
keepVarNames = false
precision = 0
version = 2022
[minify.tdewolff.json]
keepNumbers = false
precision = 0
[minify.tdewolff.svg]
keepComments = false
precision = 0
[minify.tdewolff.xml]
keepWhitespace = false
